steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cupcakes-repo/cupcakes:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cupcakes-repo/cupcakes:$COMMIT_SHA']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cupcakes-repo/cupcakes:$COMMIT_SHA' 