services:
  cupcake-app:
    container_name: cupcake-app
    env_file:
      - ./.env_services
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-5000}:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules # This prevents the host volume from overwriting container node_modules
    command: npm run dev

volumes:
  node_modules:
