version: "3"
services:
  cupcake-app:
    container_name: cupcake-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules # This prevents the host volume from overwriting container node_modules
    command: npm run dev

volumes:
  node_modules:
